# Generated by Django 5.2.7 on 2025-11-06 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('developer', 'Developer'), ('marketing', 'Marketing'), ('designer', 'Designer'), ('sales', 'Sales')], max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('posted_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
